function [] = autoFluoDetector (varargin)

%CREATING GUI
fig  =figure   ('Name','Signal Detector',...
    'NumberTitle','off',...
    'MenuBar','none',...
    'Resize','off',...
    'Color','white');
%                 'CloseRequestFcn',@obj.autoFluoDetectionClose);
%SET POSITION
try
    roiToolBoxFig=findobj('Name','ROI ToolBox');
    fig.Position=[roiToolBoxFig.Position(1) roiToolBoxFig.Position(2)-150 160 110];
catch
    fig.Position=[400 400 160 110];
end
%BUILDING UICONTROL
para               =uipanel('Title','',...
    'FontSize',9,...
    'BackgroundColor','white',...
    'Units','pixels',...
    'Position',[2 40 158 60],...
    'Parent',  fig);
%Sti radio group
sti                     =uibuttongroup('Units','pixels',...
    'BorderType','none',...
    'BackgroundColor','white',...
    'Position',[0 35 190 25],...
    'Parent',para);
allSti            =uicontrol('Style','radiobutton',...
    'String','All Sti',...
    'Position',[1 0 70 20],...
    'Value',1,...
    'Parent', sti);
individualPattern         =uicontrol('Style','radiobutton',...
    'String','Pattern',...
    'Position',[50 0 90 20],...
    'Parent',  sti);
patternEdit         =uicontrol('Style','edit',...
    'String','0',...
    'Position',[110 3 40 15],...
    'Parent',  sti);
%onoff radio group
resp                    =uibuttongroup('Units','pixels',...
    'BorderType','none',...
    'BackgroundColor','white',...
    'Position',[0 5 190 25],...
    'Parent',para);
onResp            =uicontrol('Style','radiobutton',...
    'String','ON',...
    'Position',[1 0 60 20],...
    'Value',1,...
    'Parent', resp);
offResp         =uicontrol('Style','radiobutton',...
    'String','OFF',...
    'Position',[41 0 55 20],...
    'Parent', resp);
onoffResp         =uicontrol('Style','radiobutton',...
    'String','ONOFF',...
    'Position',[87 0 60 20],...
    'Parent', resp);
% Buttons
processAutoDetectionB  =uicontrol('Style','pushbutton',...
    'String','Detect',...
    'Position',[90 10 60 25],...
    'Parent',fig,...
    'Callback',@processAutoDetection);
end