function []=fluoprocessor(varargin)

% create GUI
set(0,'defaultUicontrolBackgroundColor',[1 1 1])

fig  =figure('Name','Measure',...
                 'NumberTitle','off',...
                 'MenuBar','none',...
                 'Position',[200 200 320 300],...
                 'Resize','off',...
                 'Color','white');
%     'CloseRequestFcn',@obj.fluoChangeProcessorClose);
hpanel  =uipanel('Title','',...
    'Parent', fig,...
    'FontSize',9,...
    'Units','pixels',...
    'Position',[5 40 310 250]);
htab = uitabpanel(...
    'Parent',hpanel,...
    'TitleForegroundColor',[0 0 0],...
    'FrameBackgroundColor',[0.9412 0.9412 0.9412],...
    'TitleBackgroundColor',[0.8 0.8 0.8],...
    'PanelBackgroundColor',[1 1 1],...
    'TabPosition','lefttop',...
    'Position',[0,0,1,1],...
    'Margins',{[0,-1,1,0],'pixels'},...
    'PanelBorderType','line',...
    'Title',{'ROI','Response','Modules','Axis','Layout','Export'});

hp = getappdata(htab,'panels');
%ROI PANEL
hroi                      =uibuttongroup('Units','pixels',...
    'BorderType','none',...
    'BackgroundColor','white',...
    'Position',[20 150 190 60],...
    'Parent',hp(1));
hcurRoi              =uicontrol('Style','radiobutton',...
    'String','CurROI',...
    'Value',1,...
    'Position',[5 35 70 20],...
    'Parent', hroi);
hallRois               =uicontrol('Style','radiobutton',...
    'String','Select ROIs:',...
    'Position',[5 5 100 20],...
    'Parent', hroi,...
    'TooltipString','Choose ROI number, either single or multhiple. e.g., 85; 1:10; 1,3,5,7');
roiEdit            =uicontrol('Style','Edit',...
    'String','0',...
    'Position',[125 155 80 16],...
    'Parent', hp(1));
% RESPONSE PANEL
trail                      =uibuttongroup('Units','pixels',...
    'BorderType','none',...
    'BackgroundColor','white',...
    'Position',[20 185 190 25],...
    'Parent',hp(2));
wt          =uicontrol('Style','radiobutton',...
    'String','Raw',...
    'Position',[6 5 90 20],...
    'Parent',  trail);
tbt          =uicontrol('Style','radiobutton',...
    'String','Trail',...
    'Position',[55 5 90 20],...
    'Parent',  trail);
ave               =uicontrol('Style','radiobutton',...
    'String','Average',...
    'Value',1,...
    'Position',[110 5 70 20],...
    'Parent', trail);
filterTxt              =uicontrol('Style','radiobutton',...
    'String','Apply filter:',...
    'Value',1,...
    'Position',[25 155 100 20],...
    'Parent', hp(2));
filterEdit             =uicontrol('Style','Edit',...
    'String','0',...
    'Position',[125 155 80 16],...
    'Parent', hp(2));
selectTrailTxt              =uicontrol('Style','radiobutton',...
    'String','Select Trails:',...
    'Value',1,...
    'Position',[25 125 100 20],...
    'Parent', hp(2));
selectTrailEdit             =uicontrol('Style','Edit',...
    'String','0',...
    'Position',[125 125 80 16],...
    'Parent', hp(2));
traceLengthTxt        =uicontrol('Style','text',...
    'String','TraceLength:',...
    'Position',[35 95 85 20],...
    'Parent',hp(2));
traceLengthEdit       =uicontrol('Style','Edit',...
    'String','10',...
    'Position',[125 95 80 16],...
    'Parent',hp(2));
setBaseline                      =uibuttongroup('Units','pixels',...
    'Title','Set Baseline',...
     'FontSize',9,...
    'BackgroundColor','white',...
    'Position',[20 10 270 80],...
    'Parent',hp(2));
setBaselineLength              =uicontrol('Style','radiobutton',...
    'String','Length (s):',...
    'Value',1,...
    'Position',[5 35 80 20],...
    'Parent', setBaseline);
setBaselineLengthEdit             =uicontrol('Style','Edit',...
    'String','0',...
    'Position',[105 35 80 16],...
    'Parent', setBaseline);
setBaselineValue               =uicontrol('Style','radiobutton',...
    'String','Value:',...
    'Position',[5 5 80 20],...
    'Parent', setBaseline);
setBaselineValueEdit            =uicontrol('Style','Edit',...
    'String','0',...
    'Position',[105 5 80 16],...
    'Parent', setBaseline);
% MODULES PANEL
hds                     =uibuttongroup('Units','pixels',...
    'Title','DS Module',...
     'FontSize',9,...
    'BackgroundColor','white',...
    'Position',[20 150 270 60],...
    'Parent',hp(3));
ds              =uicontrol('Style','radiobutton',...
    'String','Detect DS',...
    'Value',1,...
    'Position',[5 15 100 20],...
    'Parent', hds);
% AXIS PANEL
axisTxt              =uicontrol('Style','radiobutton',...
    'String','Axis:',...
    'Value',1,...
    'Position',[25 185 100 20],...
    'Parent', hp(4));
yminTxt       =uicontrol('Style','text',...
    'String','Ymin:',...
    'Position',[35 155 85 20],...
    'Parent',hp(4));
yminEdit       =uicontrol('Style','Edit',...
    'String','-50',...
    'Position',[125 160 80 16],...
    'Parent',hp(4));
ymaxTxt       =uicontrol('Style','text',...
    'String','Ymax:',...
    'Position',[35 125 85 20],...
    'Parent',hp(4));
ymaxEdit       =uicontrol('Style','Edit',...
    'String','100',...
    'Position',[125 130 80 16],...
    'Parent',hp(4));
% LAYOUT PANEL
hc                     =uibuttongroup('Units','pixels',...
    'Title','Color',...
     'FontSize',9,...
    'BackgroundColor','white',...
    'Position',[20 150 270 60],...
    'Parent',hp(5));
black              =uicontrol('Style','radiobutton',...
    'String','Black',...
    'Value',1,...
    'Position',[5 15 100 20],...
    'Parent', hc);
red              =uicontrol('Style','radiobutton',...
    'String','Red',...
    'Position',[65 15 100 20],...
    'Parent', hc);
blue              =uicontrol('Style','radiobutton',...
    'String','Blue',...
    'Position',[125 15 100 20],...
    'Parent', hc);
intervalTxt       =uicontrol('Style','text',...
    'String','Interval (s):',...
    'Position',[35 115 85 20],...
    'Parent',hp(5));
intervalEdit       =uicontrol('Style','Edit',...
    'String','1',...
    'Position',[125 118 80 16],...
    'Parent',hp(5));
%EXPORT PANEL
expTxt              =uicontrol('Style','radiobutton',...
    'String','Export Data',...
    'Position',[25 185 100 20],...
    'Parent', hp(6));
filenameTxt       =uicontrol('Style','text',...
    'String','File Name:',...
    'Position',[35 155 85 20],...
    'Parent',hp(6));
filenameEdit       =uicontrol('Style','Edit',...
    'String','',...
    'Position',[125 160 80 16],...
    'Parent',hp(6));
filepathTxt       =uicontrol('Style','text',...
    'String','Save Path:',...
    'Position',[35 125 85 20],...
    'Parent',hp(6));
filepathEdit       =uicontrol('Style','Edit',...
    'String',cd,...
    'Position',[125 128 150 16],...
    'Parent',hp(6));
selectfilepathbutton=uicontrol('Style','pushbutton',...
    'String','...',...
    'Position',[280 128 16 16],...
    'Parent',hp(6),...
    'Callback',@selectSavePath);
%BUTTONS
cancelbutton       =uicontrol('Style','pushbutton',...
    'String','Cancel',...
    'Position',[180 10 60 25],...
    'Parent',fig,...
    'Callback',@cancelProcess);
processbutton            =uicontrol('Style','pushbutton',...
    'String','Process',...
    'Position',[245 10 60 25],...
    'Parent',fig,...
    'Callback',@processROI);

% 
    function []= processROI (varargin)
       
    end
end