function [g] =generateDatabase ()


g. figure = figure('Name','Cell database generator',...
                'MenuBar','none',...
                'ToolBar','none',...
                'NumberTitle','off',...
                'Resize','off',...
                'Position',[200 200 512 512]);
g.nameTxt  =uicontrol(g.figure,...
                'Style','text',...
                'BackgroundColor',get(g.figure,'Color'),...
                'String', 'Name',...
                'FontSize',9,...
                'HorizontalAlignment','left',...
                'Position',[8 480 40 20]);
g.nameEdit =uicontrol(g.figure,...
                'Style','edit',...
                'BackgroundColor','White',...
                'String', '',...
                'FontSize',9,...
                'HorizontalAlignment','left',...
                'Position',[50 480 150 20]);
g.pathTxt  =uicontrol(g.figure,...
                'Style','text',...
                'BackgroundColor',get(g.figure,'Color'),...
                'String', 'Path',...
                'FontSize',9,...
                'HorizontalAlignment','left',...
                'Position',[8 450 40 20]);
g.pathEdit =uicontrol(g.figure,...
                'Style','edit',...
                'BackgroundColor','White',...
                'String', 'C:\Users\Minggang\Google Drive\Projects\vGluT3\vglut3-GCaMP6\database',...
                'FontSize',9,...
                'HorizontalAlignment','left',...
                'Position',[50 450 150 20]);            
g.pathButton =uicontrol(g.figure,...
                'Style','pushbutton',...
                'BackgroundColor','White',...
                'String', 'Choose',...
                'FontSize',9,...
                'HorizontalAlignment','left',...
                'Position',[210 450 60 20],...
                'Callback',@choosePath);
 g.fileTxt  =uicontrol(g.figure,...
                'Style','text',...
                'BackgroundColor',get(g.figure,'Color'),...
                'String', 'Files',...
                'FontSize',9,...
                'HorizontalAlignment','left',...
                'Position',[8 420 40 20]);
g.fileList =uicontrol(g.figure,...
                'Style','listbox',...
                'BackgroundColor','White',...
                'String', '',...
                'FontSize',9,...
                'HorizontalAlignment','left',...
                'Position',[50 60 150 350],...
                'Callback',@viewFileFromList);            
g.fileButton =uicontrol(g.figure,...
                'Style','pushbutton',...
                'BackgroundColor','White',...
                'String', 'Select',...
                'FontSize',9,...
                'HorizontalAlignment','left',...
                'Position',[50 420 60 20],...
                'Callback',@selectFile);
g.filePanel =uipanel('Title','',...
                'Parent', g.figure,...
                'FontSize',9,...
                'BackgroundColor','white',...
                'Units','pixels',...
                'Position',[210 60 290 350]);            
 g.fileTab = uitabpanel(...
                'Parent',g.filePanel,...
                'TitleForegroundColor',[0 0 0],...
                'FrameBackgroundColor',[0.9412 0.9412 0.9412],...
                'TitleBackgroundColor',[0.8 0.8 0.8],... 
                'PanelBackgroundColor',[1 1 1],...
                'TabPosition','lefttop',...
                'Position',[0,0,1,1],...
                'Margins',{[0,-1,1,0],'pixels'},...
                'PanelBorderType','line',...
                'Title',{'Image Info','Stimulus Info','Notes'});
hpanel = getappdata(g.fileTab,'panels');

g.generateButton =uicontrol(g.figure,...
                'Style','pushbutton',...
                'BackgroundColor','White',...
                'String', 'Generate',...
                'FontSize',9,...
                'HorizontalAlignment','left',...
                'Position',[210 30 60 20],...
                'Callback',@gendata);
g.updateButton =uicontrol(g.figure,...
                'Style','pushbutton',...
                'BackgroundColor','White',...
                'String', 'Update',...
                'FontSize',9,...
                'HorizontalAlignment','left',...
                'Position',[280 30 60 20]);
 g.iminfoList=uicontrol('Style','listbox',...
                'BackgroundColor','White',...
                'String', 'Files',...
                'FontSize',9,...
                'HorizontalAlignment','left',...
                'Position',[0 0 285 325],...
                'Parent',hpanel(1));
  g.stiminfoTxt=uicontrol('Style','text',...
                'BackgroundColor','White',...
                'String', 'Stimulus',...
                'FontSize',9,...
                'HorizontalAlignment','left',...
                'Position',[5 5 280 315],...
                'Parent',hpanel(2));
   g.noteTxt=uicontrol('Style','text',...
                'BackgroundColor','White',...
                'String', 'Notes',...
                'FontSize',9,...
                'HorizontalAlignment','left',...
                'Position',[5 5 280 315],...
                'Parent',hpanel(3));
   g.imdata=[];
   g.stimdata=[];
   g.filedir=[];
   
% choose path            
    function []=choosePath(varargin)
        defaultPath='C:\Users\Minggang\Google Drive\Projects\vGluT3\vglut3-GCaMP6\database';
        pathname=uigetdir(defaultPath);
        set(g.pathEdit,'String', pathname);
    end

% select files
    function []=selectFile(varargin)
        filedir=uigetdir;
        cd(filedir);
        g.filedir=[g.filedir; filedir];
        
        [~,filename]=fileparts(filedir);
        shortfilename=filename(end-17:end);
        
        fileList=get(g.fileList, 'String');
        fileList=[fileList; shortfilename];
        set(g.fileList,'String', fileList);
        
        % iminfo
        name_metadata=['meta_' filename '.mat'];
        if exist(name_metadata, 'file')
            imdata=load(name_metadata);
            iminfoName=fieldnames(imdata.metadata.iminfo);
            iminfoValue=struct2cell(imdata.metadata.iminfo);
            iminfoLength=length(iminfoName);
            iminfo=cell(iminfoLength,1);
            
            for i=1:iminfoLength
                iminfo{i}=sprintf('%s : %s',iminfoName{i},num2str(iminfoValue{i}));
            end
            set(g.iminfoList, 'String', iminfo);
            set(g.iminfoList, 'Value',1);
            
            if isempty(g.imdata)
                g.imdata(1).iminfo=iminfo;
                set(g.fileList,'Value', 1);
            else
                fileN=length(g.imdata);
                g.imdata(fileN+1).iminfo=iminfo;
                set(g.fileList,'Value', fileN+1);
            end
            %stiminfo
            name_stimdata=['stim_' filename '.mat'];
            if exist(name_stimdata,'file')
                stimdata=load(name_stimdata);
                stiminfoName=fieldnames(stimdata.stidata.paraInfo);
                stiminfoNameN=length(stiminfoName);
                patN= length(stimdata.stidata.patternInfo); 
                for i=1:stiminfoNameN
                    for j=1:patN
                        stiminfoValue{i}(j)=stimdata.stidata.paraInfo(stimdata.stidata.patternInfo(j).trailN(1)).(stiminfoName{i});
                    end
                    stiminfo{i}=sprintf('%s : %s',stiminfoName{i},num2str(unique(stiminfoValue{i})));
                end
                set(g.stiminfoTxt, 'String', stiminfo);
                
                if isempty(g.stimdata)
                    g.stimdata(1).stiminfo=stiminfo;
                else
                    fileN=length(g.stimdata);
                    g.stimdata(fileN+1).stiminfo=stiminfo;
                end
            end
                
        end
            
    end

% view files from fileList
    function []=viewFileFromList(varargin)
        
        fileIndex=get(g.fileList,'Value');
        set(g.iminfoList, 'String', g.imdata(fileIndex).iminfo);
        set(g.stiminfoTxt, 'String', g.stimdata(fileIndex).stiminfo);      
    end

% generate cell database
    function []=gendata(varargin)
        
        fileN=size(g.filedir);
        cellName=get(g.nameEdit,'String');
        pathName=get(g.pathEdit,'String');
        fullCellName=fullfile(pathName,cellName);
        for i=1:fileN(1)
            cd(g.filedir(i,:));
            [~,newdir]=fileparts(g.filedir(i,:));
            mkdir(fullCellName, newdir);
            copyfile('*.mat', fullfile(fullCellName, newdir));
        end
        data.filedir=g.filedir;
        data.imdata=g.imdata;
        data.stimdata=g.stimdata;
        cd(fullCellName);
        save(['info_' cellName], 'data');
    end
end