function g =generateCell (varargin)


g.figure = figure('Name','Cell generator',...
    'MenuBar','none',...
    'ToolBar','none',...
    'NumberTitle','off',...
    'Resize','off',...
    'Position',[200 200 512 512]);
g.nameTxt  =uicontrol(g.figure,...
    'Style','text',...
    'BackgroundColor',get(g.figure,'Color'),...
    'String', 'Name',...
    'FontSize',9,...
    'HorizontalAlignment','left',...
    'Position',[8 480 40 20]);
g.nameEdit =uicontrol(g.figure,...
    'Style','edit',...
    'BackgroundColor','White',...
    'String', '',...
    'FontSize',9,...
    'HorizontalAlignment','left',...
    'Position',[50 480 150 20]);
g.pathTxt  =uicontrol(g.figure,...
    'Style','text',...
    'BackgroundColor',get(g.figure,'Color'),...
    'String', 'Path',...
    'FontSize',9,...
    'HorizontalAlignment','left',...
    'Position',[8 450 40 20]);
g.pathEdit =uicontrol(g.figure,...
    'Style','edit',...
    'BackgroundColor','White',...
    'String', 'C:\Users\Minggang\Google Drive\Projects\vGluT3\vglut3-GCaMP6\database',...
    'FontSize',9,...
    'HorizontalAlignment','left',...
    'Position',[50 450 150 20]);
g.pathButton =uicontrol(g.figure,...
    'Style','pushbutton',...
    'BackgroundColor','White',...
    'String', 'Choose',...
    'FontSize',9,...
    'HorizontalAlignment','left',...
    'Position',[210 450 60 20],...
    'Callback',@choosePath);
g.fileTxt  =uicontrol(g.figure,...
    'Style','text',...
    'BackgroundColor',get(g.figure,'Color'),...
    'String', 'Files',...
    'FontSize',9,...
    'HorizontalAlignment','left',...
    'Position',[8 420 40 20]);
g.fileList =uicontrol(g.figure,...
    'Style','listbox',...
    'BackgroundColor','White',...
    'String', '',...
    'FontSize',9,...
    'HorizontalAlignment','left',...
    'Position',[50 60 150 350],...
    'Callback',@viewFileFromList);
g.fileButton =uicontrol(g.figure,...
    'Style','pushbutton',...
    'BackgroundColor','White',...
    'String', 'Select',...
    'FontSize',9,...
    'HorizontalAlignment','left',...
    'Position',[50 420 60 20],...
    'Callback',@selectFile);
g.filePanel =uipanel('Title','',...
    'Parent', g.figure,...
    'FontSize',9,...
    'BackgroundColor','white',...
    'Units','pixels',...
    'Position',[210 60 290 350]);
g.fileTab = uitabpanel(...
    'Parent',g.filePanel,...
    'TitleForegroundColor',[0 0 0],...
    'FrameBackgroundColor',[0.9412 0.9412 0.9412],...
    'TitleBackgroundColor',[0.8 0.8 0.8],...
    'PanelBackgroundColor',[1 1 1],...
    'TabPosition','lefttop',...
    'Position',[0,0,1,1],...
    'Margins',{[0,-1,1,0],'pixels'},...
    'PanelBorderType','line',...
    'Title',{'Notes','Cell Summary'});
hpanel = getappdata(g.fileTab,'panels');

g.generateButton =uicontrol(g.figure,...
    'Style','pushbutton',...
    'BackgroundColor','White',...
    'String', 'Generate',...
    'FontSize',9,...
    'HorizontalAlignment','left',...
    'Position',[210 30 60 20],...
    'Callback',@gendata);
g.updateButton =uicontrol(g.figure,...
    'Style','pushbutton',...
    'BackgroundColor','White',...
    'String', 'Update',...
    'FontSize',9,...
    'HorizontalAlignment','left',...
    'Position',[280 30 60 20]);
g.iminfoList=uicontrol('Style','text',...
    'BackgroundColor','White',...
    'String', 'Files',...
    'FontSize',9,...
    'HorizontalAlignment','left',...
    'Position',[0 0 285 325],...
    'Parent',hpanel(1));
g.cellSummary=uicontrol('Style','edit',...
    'BackgroundColor','White',...
    'String', '',...
    'FontSize',9,...
    'Max', 10,...
    'HorizontalAlignment','left',...
    'Position',[5 5 280 315],...
    'Parent',hpanel(2));



if nargin && iscell(varargin{1})
    
    g.filedir = varargin{1};
    loadInfo;
    
% elseif nargin && isstruct(varargin{1}) 
%     g.filedir = varargin{1}.filedir;
% %      loadInfo;
%     
%     g.imdata  = varargin{1}.imdata;
%     g.celldata=  varargin{1}.celldata;
%     set(g.cellSummary,'String',g.celldata);
else
    g.imdata=[];
    g.filedir=[];
end


    function [] = loadInfo (varargin)
        fileN = length(g.filedir);
        
        for i = 1:fileN
            filedir = g.filedir{i};
            cd(filedir);
            [~,filename]=fileparts(filedir);
            shortFilename=filename(end-17:end);
            
            fileList=get(g.fileList, 'String');
            fileList=[fileList; shortFilename];
            set(g.fileList,'String', fileList);
            set(g.fileList, 'Value',i);
            
            % iminfo
            name_metadata=['meta_' filename '.mat'];
            if exist(name_metadata, 'file')
                imdata = load(name_metadata);
                if isfield(imdata.metadata,'notes')
                    g.imdata(i).notes = imdata.metadata.notes;
                else
                    g.imdata(i).notes = '';
                end
                set(g.iminfoList, 'String', g.imdata(i).notes);
%                 set(g.iminfoList, 'Value',i);
            end
        end
    end

% choose path
    function []=choosePath(varargin)
        defaultPath='C:\Users\Minggang\Google Drive\Projects\vGluT3\vglut3-GCaMP6\database';
        pathname=uigetdir(defaultPath);
        set(g.pathEdit,'String', pathname);
    end

% select files
    function []=selectFile(varargin)
        
        selectFileNames = selectBatchFromFolder;
        g.filedir = selectFileNames;       
        loadInfo; 
        
    end

% view files from fileList
    function []=viewFileFromList(varargin)
        
        fileIndex=get(g.fileList,'Value');
        set(g.iminfoList, 'String', g.imdata(fileIndex).notes);
    end

% generate cell database
    function []=gendata(varargin)
        
        fileN=length(g.filedir);
        cellName=get(g.nameEdit,'String');
        pathName=get(g.pathEdit,'String');
        fullCellName=fullfile(pathName,cellName);
        for i=1:fileN
            cd(g.filedir{i});
            [~,filename{i}]=fileparts(g.filedir{i});
            newfullName{i} = fullfile(fullCellName, filename{i});
            mkdir(fullCellName, filename{i});
            copyfile('*.mat', newfullName{i});
        end
        data.filedir = filename;
        data.iminfo=g.imdata;
        data.cellinfo=get(g.cellSummary,'String');
        cd(fullCellName);
        save(['info_' cellName], 'data');
        delete(g.figure);
    end
end